export { default as SelectImg } from "./Polygon 17.svg";
export { default as SuccessImg } from "./checked.png";
export { default as FailImg } from "./failed.png";
export { default as WaitImg } from "./wait.png";
export { default as DownLoadImg } from "./Vector.svg";
export { default as ArrowBack } from "./Arrow back.svg";
export { default as CheckImg } from "./checked1.png";
export { default as CheckBlack } from "./checked (1).png";
export { default as CancelImg } from "./checked3.png";
export { default as CancelBlack } from "./failedblack.png";
export { default as FileDownImg } from "./file 2.png";
export { default as TriAngle } from "./Polygon 11.svg";
